project_name: "mother-of-necessity"
author_fullname: "Pete Kunhardt"
preferred_name: "kunhardt"

projects:

  "The Airplane Problem":
    description: |
      Brute forcing the classic algorithmic thinking problem to win an internet argument.
    tags:
      - "probability"
      - "python"
      - "recursion"
    elements:
      - readme: "/misc-fun/airplane-problem-bruteforce/README.md"
      - code: "/misc-fun/airplane-problem-bruteforce/proof.py"
      - commands:
        - "Simulate Once": |
          "import proof;"
          "passenger_order = proof.generate_random_passenger_order();"
          "results = proof.fill_cabin(passenger_order);"
          "print(results);"
        - "Simulate 50k & Summarize": |
          "import proof;"
          "proof.main();"


  "Validating Hierarchical JSON":
    desctription: |
      Validating and warehousing an uncertain-depth hierarchical JSON balance sheet.
    tags:
      - "ETL"
      - "json"
      - "python"
    elements:
      - readme: "/technical-assessments/validating-hierarchical-json/README.md"
      - code: "/technical-assessments/validating-hierarchical-json/validate_balance_sheet_json.py"
      - commands:
        - "Validate Original": |
          "import validate_balance_sheet_json as vdate;"
          "vdate.main([\"--file\", \"json-validation/balance_sheet_imports.json\"]);"
        - "Validate Error-Ridden Version": |
          "import validate_balance_sheet_json as vdate;"
          "vdate.main([\"--file\", \"json-validation/balance_sheet_imports_with_fake_errors.json\"]);"
          "vdate.main([\"--file\", \"json-validation/balance_sheet_imports_with_fake_errors.json\"]);"
