name: "mother-of-necessity"


tiles:

  "The Airplane Problem":
    subtiles:
      - readme: "/misc-fun/airplane-problem-bruteforce/README.md"
        position: "left"
      - code: "/misc-fun/airplane-problem-bruteforce/proof.py"
        position: "center"
      - commands:
        - "Simulate Once": |
          "import proof;"
          "passenger_order = proof.generate_random_passenger_order();"
          "results = proof.fill_cabin(passenger_order);"
          "print(results);"
        - "Simulate 50k & Summarize": |
          "import proof;"
          "proof.main();"
        position: "right"


  "Validating Hierarchical JSON":
    subtiles:
      - readme: "/technical-assessments/validating-hierarchical-json/README.md"
        position: "left"
      - code: "/technical-assessments/validating-hierarchical-json/validate_balance_sheet_json.py"
        position: "left"
      - commands:
        - "Validate Original": |
          "import validate_balance_sheet_json as vdate;"
          "vdate.main([\"--file\", \"json-validation/balance_sheet_imports.json\"]);"
        - "Validate Error-Ridden Version": |
          "import validate_balance_sheet_json as vdate;"
          "vdate.main([\"--file\", \"json-validation/balance_sheet_imports_with_fake_errors.json\"]);"
        position: "right"