name: "mother-of-necessity"

executables:
  misc-fun:
    airplane-problem-bruteforce: 
      proof.py:
        commands:
          - "Simulate Once": "python -c \"import proof; passenger_order = proof.generate_random_passenger_order(); proof.fill_cabin(passenger_order)\""
          - "Simulate 50k & Summarize": "python proof.py"

  technical-assessments:
    validating-hierarchical-json:
      json-validation:
        validate_balance_sheet_json.py:
          commands:
            - "Validate Original": "python \"validate_balance_sheet.py\" --file balance_sheet_imports.json"
            - "Validate Error-Ridden Version": "python \"validate_balance_sheet.py\" --file balance_sheet_imports_with_fake_errors.json"
